model:
  #target: ldm.models.diffusion.ddpm.LatentDiffusion
  target: cldm.cldm.ControlLDM
  version: "1.5"
  #pretrained_ckpt: "models/control_segmentation_sd_v1.5_static-77bea2e9.ckpt" # change it to ckpt corresponding to certain control mode
  prediction_type: "noise" # Note: set to "v" if trained with v objective
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "caption"
    image_size: 64
    channels: 4
    cond_stage_trainable: False
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    use_fp16: True

    unet_config:
      target: cldm.cldm.ControlnetUnetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        guess_mode: False
        strength: 1.0
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        use_fp16: True
        dropout: 0.
        use_recompute: False
        enable_flash_attention: False
        upcast_attn: True
        upcast_sigmoid: True
        sd_locked: True
        # only_mid_control: False # TODO: impl later

        control_stage_config:
          target: cldm.cldm.ControlNet
          params:
            image_size: 32 # unused
            in_channels: 4
            hint_channels: 3
            model_channels: 320
            attention_resolutions: [ 4, 2, 1 ]
            num_res_blocks: 2
            channel_mult: [ 1, 2, 4, 4 ]
            num_heads: 8
            use_spatial_transformer: True
            transformer_depth: 1
            context_dim: 768
            use_checkpoint: True
            legacy: False
            use_fp16: True
            dropout: 0.
            upcast_attn: True
            upcast_sigmoid: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        upcast_sigmoid: True
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        use_fp16: True

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
        use_fp16: True
        tokenizer_name: "BpeTokenizer"
        context_length: 77
        vocab_size: 49408
        output_dim: 768
        width: 768
        layers: 12
        heads: 12
        epsilon: 1e-7
        use_quick_gelu: True
        upcast_attn: True
