# model
model_version: v1.1
pretrained_model_path: "models/PixArt-XL-2-1024-MS.ckpt"
model_max_length: 200

enable_flash_attention: True
use_recompute: True

# data
image_size: [ 512, 512 ]
num_frames: 16
frame_stride: 3

num_parallel_workers: 16
max_rowsize: 256

# precision
amp_level: "O2"
dtype: "bf16"
init_loss_scale: 65536

# training hyper-params
scheduler: "cosine_decay"
start_learning_rate: 1.e-4
end_learning_rate: 2.e-5
warmup_steps: 500   # TODO: ablate

batch_size: 1
clip_grad: True
max_grad_norm: 5.0
use_ema: False

optim: "adamw_re"
optim_eps: 1.e-8
weight_decay: 0.

epochs: 2000
ckpt_save_interval: 100

mask_ratios:
  mask_no: 0.75
  mask_quarter_random: 0.025
  mask_quarter_head: 0.025
  mask_quarter_tail: 0.025
  mask_quarter_head_tail: 0.05
  mask_image_random: 0.025
  mask_image_head: 0.025
  mask_image_tail: 0.025
  mask_image_head_tail: 0.05

bucket_config:
  # Structure: resolution: { num_frames: [ keep_prob, batch_size ] }
  # Setting [ keep_prob, batch_size ] to [ 0.0, 0 ] forces longer videos into smaller resolution buckets
  "144p": { 1: [ 0.5, 48 ], 16: [ 1.0, 6 ], 32: [ 1.0, 3 ], 96: [ 1.0, 1 ] }
  "256": { 1: [ 0.5, 24 ], 16: [ 0.5, 3 ], 48: [ 0.5, 1 ], 64: [ 0.0, 0 ] }
  "240p": { 16: [ 0.3, 2 ], 32: [ 0.3, 1 ], 64: [ 0.0, 0 ] }
  "512": { 1: [ 0.4, 12 ] }
  "1024": { 1: [ 0.3, 3 ] }
