TASK_TYPE: SINGLE_TASK
read_image: True # You NEED Open It
read_style: True
ENABLE: true
DATASET: webvid10m
video_compositions: ['text', 'mask', 'depthmap', 'sketch', 'motion', 'image', 'local_image', 'single_sketch']
guidances: ['y', 'local_image', 'image', 'motion'] # You NEED Open It
vit_image_size: 224
network_name: UNetSD_temporal
resume: true
resume_step: 228000
seed: 182
num_workers: 0
mvs_visual: False
chunk_size: 1
resume_checkpoint: "non_ema_228000-3bb2ee9a.ckpt"
log_dir: 'outputs'
num_steps: 1
learning_rate: 0.00001 #0.00005 in paper, but we are finetuning.
