# model
space_scale: 1.0  # 0.5 for 256. 1.0 for 512
time_scale: 0.6666666667
pretrained_model_path: "models/PixArt-XL-2-512x512.ckpt"

sd_scale_factor: 0.18215
enable_flash_attention: False

# data
image_size: 512
num_frames: 64
frame_stride: 2

# precision
dtype: "fp16"
init_loss_scale: 65536

# training hyper-params
scheduler: "constant"
start_learning_rate: 2.e-5
end_learning_rate: 2.e-5
warmup_steps: 0   # TODO: ablate

batch_size: 2
clip_grad: True
use_ema: True # TODO: ablate

optim: "adamw_re"
optim_eps: 1.e-8
weight_decay: 0.

epochs: 2000
ckpt_save_interval: 100
