environment:
  mode: 0
  debug: False
  seed: 42
  distributed: True
  enable_modelarts: False

train:
  epochs: 10
  output_dir: output/t2i_adapter_v2.1/

  dataset:
    class_path: examples.stable_diffusion_v2.ldm.data.dataset_with_cond.COCOStuff
    init_args:
      image_dir:
      masks_path:
      label_path:

  dataloader:
    batch_size: 8
    shuffle: True
    drop_remainder: True

  optimizer:
    name: adamw
    lr: 1.0e-5
    betas: [ 0.9, 0.999 ]
    weight_decay: 0.01

  settings:
    drop_overflow_update: True
    gradient_accumulation_steps: 1
    clip_grad: False
    clip_norm: 1.0

sd_config: ../stable_diffusion_v2/configs/v2-inference.yaml
sd_ckpt: models/sd_v2-1_base-7c8d09ce.ckpt

adapter:
  condition: segmentation
  use_fp16: False           # Train in full-precision, inference in half-precision

LossScale:
  loss_scale_value: 65536
  scale_factor: 2
  scale_window: 1000
