env:
  mode: 0
  jit_level: O0
  seed: 42
  distributed: False
  debug: False

model:
  name: llama-1B
  pretrained_model_path:
  enable_flash_attention: True
  dtype: bf16

vae:
  ckpt_path: models/OpenSora-VAE-v1.2/model.ckpt
  dtype: fp16

# Inference parameters
num_sampling_steps: 50
sample_method: linear-quadratic
image_size: [ 256, 256 ]
num_frames: 1   # image
text_emb:
  ul2_dir:
  metaclip_dir:
  byt5_dir:
batch_size: 10

# Saving options
output_path: samples
append_timestamp: True
save_format: png
save_latent: False
